[
    { "name": "Akira Expanded Super Bold", "file": "Akira Expanded_Super Bold.json" },
    { "name": "American Captain", "file": "American Captain_Regular.json" },
    { "name": "Bebas Neue", "file": "Bebas Neue_Regular.json" },
    { "name": "Bestime", "file": "Bestime_Regular.json" },
    { "name": "Caviar Dreams Bold", "file": "Caviar Dreams_Bold.json" },
    { "name": "Caviar Dreams", "file": "Caviar Dreams_Regular.json" },
    { "name": "Chewy Bubble", "file": "Chewy Bubble_Regular.json" },
    { "name": "Chonky Bunny", "file": "Chonky Bunny_Regular.json" },
    { "name": "Cocogoose Pro Trial Bold", "file": "Cocogoose Pro Trial Bold_Regular.json" },
    { "name": "Cocogoose Pro Trial", "file": "CocogooseProTrial_Regular.json" },
    { "name": "Coolvetica Heavy Comp", "file": "Coolvetica Heavy Comp_Regular.json" },
    { "name": "Cream Cake", "file": "Cream Cake_Regular.json" },
    { "name": "Gloomie Saturday", "file": "Gloomie Saturday_Regular.json" },
    { "name": "Heavitas", "file": "Heavitas_Regular.json" },
    { "name": "Internets", "file": "Internets_Regular.json" },
    { "name": "KG Perfect Penmanship", "file": "KG Perfect Penmanship_Regular.json" },
    { "name": "LEMON MILK Bold Italic", "file": "LEMON MILK Bold Italic.json" },
    { "name": "LEMON MILK", "file": "LEMON MILK_Regular.json" },
    { "name": "Million Design", "file": "Million Design_Regular.json" },
    { "name": "Minecraft Medium", "file": "Minecraft_Medium.json" },
    { "name": "Nexa Heavy", "file": "Nexa Heavy_Regular.json" },
    { "name": "Roboto Bold", "file": "Roboto_Bold.json" },
    { "name": "Roboto", "file": "Roboto_Regular.json" },
    { "name": "Starbim", "file": "Starbim_Regular.json" },
    { "name": "Starborn", "file": "Starborn_Regular.json" },
    { "name": "Story of Lala", "file": "Story of Lala_Regular.json" },
    { "name": "Unageo Bold", "file": "Unageo_Bold.json" },
    { "name": "Unageo", "file": "Unageo_Regular.json" }
  ]
